name: Build and deploy Python app to Azure Web App - DreamInCode

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: DreamInCode           # <-- Cambia si tu App Service tiene otro nombre
  AZURE_RESOURCE_GROUP: DreamInCode-rg     # <-- Cambia al Resource Group real
  PYTHON_VERSION: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      - name: Prepare clean deploy package (zip)
        run: |
          set -e

          STAGING="${RUNNER_TEMP}/staging"
          mkdir -p "$STAGING"

          # Copia solo lo necesario, excluyendo artefactos y carpetas que te
          # metían ruido en el ZIP (check/, deploy/, _preview/, zips, etc.)
          rsync -a \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude ".vscode/" \
            --exclude "__pycache__/" \
            --exclude "*.pyc" \
            --exclude "*.pyo" \
            --exclude "*.zip" \
            --exclude "check/" \
            --exclude "deploy/" \
            --exclude "_preview/" \
            ./ "$STAGING/"

          # Sanity checks que te evitan el ModuleNotFoundError: mcp_api
          test -f "$STAGING/application.py" || (echo "::error::No se encontró application.py en la raíz" && exit 1)
          test -d "$STAGING/mcp_api" || (echo "::error::No se encontró la carpeta 'mcp_api/'" && exit 1)
          test -f "$STAGING/requirements.txt" || (echo "::error::No se encontró requirements.txt" && exit 1)
          
          if ! grep -q "gunicorn" "$STAGING/requirements.txt"; then
            echo "gunicorn==21.2.0" >> "$STAGING/requirements.txt"
          fi

          # Empaqueta lo limpio
          cd "$STAGING"
          zip -r "${GITHUB_WORKSPACE}/deploy.zip" . -x "*.pyc" "*__pycache__*"

      - name: Upload artifact (deploy.zip)
        uses: actions/upload-artifact@v4
        with:
          name: deploy-zip
          path: deploy.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DreamInCode'
          slot-name: 'production'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: .